name: example
description: "Sliver Center Example Project"
publish_to: 'none'
homepage: https://github.com/DemienIlnutskiy/sliver_center

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sliver_center: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true