name: sliver_center
description: "Sliver Center For CustomScrollView"
version: 0.0.1+2
homepage: https://github.com/DemienIlnutskiy/sliver_center

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

